
```{r}
setwd("D:/R/Udacity/EDA_Course_Materials/lesson4")
```

# Diamonds

## price vs. x
```{r}
library(ggplot2)
ggplot(diamonds, aes(price, x)) + geom_point()

```
## price vs. depth
```{r}
qplot(price, depth, data = diamonds, colour = cut) 
```

## other variant of price vs.depth (+adjastments)
```{r}
ggplot(data = diamonds, aes(x = depth, y = price)) + 
  geom_point(alpha=0.1) +
  scale_x_continuous(breaks = seq(0,80,2))
cor(diamonds$depth, diamonds$price)
```

## price vs. carat
```{r}
qplot(carat, price, data = diamonds) +

    scale_x_continuous(lim = c(0,2.18), breaks = seq(0,2.18,0.25)) +
    scale_y_continuous(lim = c(0, 17378), breaks = seq(0,17378,500))

```

## price vs. volume
```{r}
# create new column
diamonds$volume = diamonds$x * diamonds$y * diamonds$z
new_data <- subset(diamonds, volume != 0 & volume < 800)

ggplot(aes(x=volume, y=price), data = new_data) +
    geom_point(alpha=0.1) +
    stat_smooth(method = "lm", formula = y ~ x + I(x^0.3), size = 1) +
    scale_x_continuous(lim = c(0,800), breaks = seq(0,800,50)) +
    scale_y_continuous(lim = c(0, 19000), breaks = seq(0,19000,1000))
cor(new_data$price, new_data$volume)
```

## mean price by clarity
```{r}
library(dplyr)
a <- group_by(diamonds, clarity)
diamondsByClarity <- summarise(a, mean_price = mean(price), median_price = median(price), min_price = min(price), max_price = max(price), n = n())
select(diamondsByClarity, -clarity)
```
## bar charts of mean price
```{r}
library(dplyr)
library(gridExtra)

diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))

p1 = ggplot(diamonds_mp_by_clarity, 
            aes(x = clarity, y = mean_price)) + 
            labs(title = "diamonds_mp_by_clarity") +
            geom_bar(stat='identity') 
p2 = ggplot(diamonds_mp_by_color, 
            aes(x = color, y = mean_price)) + 
            labs(title = "diamonds_mp_by_color") +
            geom_bar(stat='identity') 

grid.arrange(p1, p2, ncol = 1)
```
